
default: build_probable-potato

.PHONY: build_probable-potato

HOME = "../../.."

build_probable-potato: main.cpp
	@echo "Starting compilation of 'probable-potato'"
	${GXX} ${GXXFLAGS} main.cpp -o "${TARGET_DIR}/probable-potato"
